import { mkdir, writeFile, readdir, stat } from 'node:fs/promises'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const outDir = join(here, '..', 'src', 'assets', 'fonts')

// Only these subsets are needed: the article is Russian + Latin legal abbreviations.
const KEEP_SUBSETS = new Set(['cyrillic', 'latin'])

const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36'

// Italic is only carried by Playfair Display (variable) — PT Serif ships four
// separate static italics that would add ~140 KB of base64 for a role the
// display face already covers.
const FAMILIES = [
  { css: 'Playfair+Display:ital,wght@0,400..900;1,400..900', file: 'playfair-display' },
  { css: 'PT+Serif:wght@400;700', file: 'pt-serif' },
  { css: 'Onest:wght@400..800', file: 'onest' },
]

async function main() {
  await mkdir(outDir, { recursive: true })

  const url =
    'https://fonts.googleapis.com/css2?' +
    FAMILIES.map((f) => `family=${f.css}`).join('&') +
    '&display=swap'

  const res = await fetch(url, { headers: { 'User-Agent': UA } })
  if (!res.ok) throw new Error(`Google Fonts CSS: ${res.status}`)
  let css = await res.text()

  // Google serves several @font-face blocks per family, one per subset,
  // each preceded by a /* cyrillic */ style comment.
  const blocks = css.split(/(?=\/\*\s*[a-z-]+\s*\*\/)/g).filter((b) => b.includes('@font-face'))
  const kept = []

  for (const block of blocks) {
    const subset = /\/\*\s*([a-z-]+)\s*\*\//.exec(block)?.[1] ?? ''
    if (!KEEP_SUBSETS.has(subset)) continue
    const src = /url\((https:[^)]+\.woff2)\)/.exec(block)?.[1]
    if (!src) continue
    const file = src.split('/').slice(-3).join('-').replace(/[^\w.-]/g, '_')
    const bin = Buffer.from(await (await fetch(src, { headers: { 'User-Agent': UA } })).arrayBuffer())
    await writeFile(join(outDir, file), bin)
    kept.push({ subset, file, bytes: bin.length, block })
    process.stdout.write(`${file.padEnd(34)} ${subset.padEnd(11)} ${(bin.length / 1024).toFixed(1)} KB\n`)
  }

  if (kept.length === 0) throw new Error('no font faces matched — aborting')

  // Emit a self-contained fonts.css pointing at local files.
  const seen = new Set()
  let out = '/* Generated by scripts/fetch-fonts.mjs — do not edit by hand. */\n'
  out += '/* Playfair Display, PT Serif and Onest are licensed under the SIL Open Font License 1.1. */\n\n'
  for (const k of kept) {
    const body = k.block
      .replace(/\/\*[^*]*\*\/\s*/, '')
      .replace(/url\(https:[^)]+\.woff2\)/g, `url('../assets/fonts/${k.file}')`)
      .trim()
    // de-duplicate identical faces (Google emits a comment per subset, we already
    // filter, but a variable family can repeat the same file across weights)
    const sig = body.replace(/font-style:\s*normal/g, '').replace(/font-weight:\s*[^;]+;/g, '')
    if (seen.has(sig)) continue
    seen.add(sig)
    out += `/* ${k.subset} */\n${body}\n\n`
  }
  await writeFile(join(here, '..', 'src', 'styles', 'fonts.css'), out, 'utf8')

  const total = kept.reduce((n, k) => n + k.bytes, 0)
  console.log(`\n${kept.length} faces, ${(total / 1024).toFixed(1)} KB raw -> base64 in single-file build: ~${((total * 1.34) / 1024).toFixed(1)} KB`)
  console.log('files in', outDir, (await readdir(outDir)).length)
  await stat(join(here, '..', 'src', 'styles', 'fonts.css'))
}

main().catch((e) => {
  console.error(e)
  process.exit(1)
})
